@startuml Classes
skinparam shadowing false

class HTTPTransceiver {
 -version
 +receive_request()
 +transmit_response()
}

class Request {
  +str method
  +str url
  +str version
  +get_parameter(key: str) -> str
  +get_parameter_int(key: str) -> int
  +get_header(key: str) -> str
}
@enduml