@startuml Classes
skinparam shadowing false

class HTTPTransceiver {
 -user_agent
 +receive_request()
 +transmit_response()
}

class Request {
  -Dict[str, str] parameters
  +getParameter(name: str) -> str
}
@enduml